sudo: required
services:
        - docker


before_install:
        - docker build -t ishah011/docker-react -f Dockerfile.dev .

script:
        - docker run ishah011/docker-react npm run test -- --coverage
